name: example
description: A new Flutter project to demonstrate the use of the expirable_widget package.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  expirable_widget:
    path: ../

  flutter:
    sdk: flutter
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
