name: expiring package test
on:
  pull_request:
    branches:
      - master
  
  push:
    branches:
      - '**'
      - '!master'
jobs:
  flutter_test:
    name: Run flutter test on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test